name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-electron-app
          path: release-builds/
          
      - name: Extract release notes from CHANGELOG.md
        id: notes
        run: |
          # Extract the first section from CHANGELOG.md
          NOTES=$(awk '/^## /{if (p) exit; p=1} p' CHANGELOG.md)
          echo "::set-output name=notes::$NOTES"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-builds/*.exe
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
